name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: |
          echo "Hello World!"
          echo "From Rateb:D"
      - name: Print GoodBye
        run: echo "Done - bye!"
